### ISSUE TITLE
Warping Broken over ~100,000M

### ISSUE THREAD

**Issue by willbill642** [LunaMultiplayer/LunaMultiplayer#263]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10 EDU 1803/ Pro 1809

------------------------------------------------------------------------------

KSPVersion: 1.6

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.20.0

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: You can time warp like in atmosphere.

------------------------------------------------------------------------------

Current behaviour: Depending on luck and whether you're in the map, warping above ~100,000M of Kerban results in one or more of the following: A complete loss in velocity, an invisible craft, a destroyed craft, a phantom craft on the launch pad regardless of previous mission length, and a mostly non-functional space center menu (disconnecting and rejoining from the LMP menu will fix this last issue)

------------------------------------------------------------------------------

Steps to reproduce: Fly any craft above ~100,000M, 200,000M is especially awful. Start at 1x time, then increase warp to any amount above. Tested with both hotkeys and menu keys. Other notes: had a second person present in game, but their status did not change the results.

Config, Logs, and Universe. Not run in debug mode but so consistent to reproduce you shouldn't have an issue. 
[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2729197/LMPServer.zip)
[KSP.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2729210/KSP.zip)
[output_log.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2729211/output_log.zip)

**Comment by AdamRidley** [comment]
I'm having exactly the same issue on the same build with save version. It is effortless to reproduce but if you need any logs from me then let me know!

**Comment by willbill642** [comment]
[FLIGHT GLOBALS]: Switching To Vessel untitled mkII.V ---------------------- 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Camera Mode: AUTO
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

all systems started
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UIMasterController]: ShowUI
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[LMP] Adjusted time from: 370201.272430681 to: 370206.293437673 due to error: -5021.00699202856
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UiApp] Awake: CurrencyWidgetsApp
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UiApp] Awake: ResourceDisplay
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UiApp] Awake: KSPedia
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UiApp] Awake: Missions App
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UiApp] Awake: DeltaVApp
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[ApplicationLauncher] OnSceneLoadedGUIReady: scene FLIGHT ShouldBeVisible() True ShouldBeOnTop() True iIsPositionedAtTop False
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[ApplicationLauncher] SpawnSimpleLayout: VerticalTopDown
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ScaleModList: listSize 41 maxListSize 1157
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[KnowledgeBase] OnAppLauncherReady 61932
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UIApp] OnDestroy: Contracts
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[MessageSystem] Reposition 0.02 61933
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[GenericAppFrame] Reposition 0.02 61933
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[GenericAppFrame] Reposition 0.02 61933
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ObT : NaN
M : NaN
E : NaN
V : NaN
Radius: NaN
vel: [NaN, NaN, NaN]
AN: [91809.3863414175, 1709259.90432262, 0]
period: Infinity

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[LMP - OrbitDriver Warning!]: fuckin untitled mkII.V had a NaN Orbit and was removed.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

fuckin untitled mkII.V Unloaded
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[LMP]: Removing 783e62af-09af-4e62-8f39-57d141534b21 from the server
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[LMP]: Killing vessel 783e62af-09af-4e62-8f39-57d141534b21. Reason: Corrupt vessel orbit
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[UIMasterController]: HideUI
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[HighLogic]: =========================== Scene Change : From FLIGHT to SPACECENTER (Async) =====================

Just did some digging, looks like the issue stems from the Orbit not being properly (see: at all) synced during either flight reload or warp. Also, if you're in the space center and try to fly a craft above the ~100,000M mark from the tracking center, the same issue occurs.

**Comment by limerox** [comment]
Same here with KSP: 1.6 and LMP: 0.20.0 .

The server (debug version) log shows nothing special.

Issue is maybe caused by changing HarmonyPatches for LMPClient with commit 290335eb75cefa0ebda2f0ec885eec847778023d.

Here are the relevant lines from the logs i found ;)
by the way, @gavazquez thank you very much for your work


---
### **output_log**

[LMP]: Locked to subspace -1, time: 5013.0147621
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LmpClient.LunaLog:Log(String)
LmpClient.Systems.Warp.WarpSystem:set_CurrentSubspace(Int32)
LmpClient.Systems.Warp.WarpEvents:OnTimeWarpChanged()
EventVoid:Fire()
TimeWarp:assumeWarpRate(Single, Boolean, Boolean)
TimeWarp:setRate(Int32, Boolean, Boolean, Boolean, Boolean)
TimeWarp:SetRate_Patch1(Int32, Boolean, Boolean)
KSP.UI.UITimeWarpController:ClickTimewarp1()
UnityEngine.Events.InvokableCall:Invoke() (at C:\buildslave\unity\build\Runtime\Export\UnityEvent.cs:160)
UnityEngine.Events.UnityEvent:Invoke() (at C:\buildslave\unity\build\Runtime\Export\UnityEvent_0.cs:58)
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs Line: 160)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Orbit:GetDTforTrueAnomaly(Double, Double)
PatchedConics:_CalculatePatch(Orbit, Orbit, Double, SolverParameters, CelestialBody)
PatchedConicSolver:Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Orbit:GetDTforTrueAnomaly(Double, Double)
PatchedConics:_CalculatePatch(Orbit, Orbit, Double, SolverParameters, CelestialBody)
PatchedConicSolver:Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Orbit:GetDTforTrueAnomaly(Double, Double)
PatchedConics:_CalculatePatch(Orbit, Orbit, Double, SolverParameters, CelestialBody)
PatchedConicSolver:Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Orbit:GetDTforTrueAnomaly(Double, Double)
PatchedConics:_CalculatePatch(Orbit, Orbit, Double, SolverParameters, CelestialBody)
PatchedConicSolver:Update()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Packing Pegasus for orbit
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
Vessel:GoOnRails_Patch1(Object)
OrbitPhysicsManager:LateUpdate()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ObT : NaN
M : NaN
E : NaN
V : NaN
Radius: NaN
vel: [NaN, NaN, NaN]
AN: [-0.121126667573523, -0.0440197525915566, 0]
period: Infinity

UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
LmpClient.Harmony.OrbitDriver_UpdateFromParameters:UpdateFromParameters(OrbitDriver, Double&)
LmpClient.Harmony.OrbitDriver_UpdateFromParameters:PrefixUpdateFromParameters(OrbitDriver, Double&)
OrbitDriver:updateFromParameters_Patch1(Object)
LmpClient.Harmony.OrbitDriver_UpdateOrbit:UpdateOrbit(OrbitDriver, Boolean, Boolean&, Double&, Boolean&)
LmpClient.Harmony.OrbitDriver_UpdateOrbit:PrefixUpdateOrbit(OrbitDriver, Boolean, Boolean&, Double&, Boolean&)
OrbitDriver:UpdateOrbit_Patch1(Object, Boolean)
VesselPrecalculate:MainPhysics(Boolean)
VesselPrecalculate:FixedUpdate()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[LMP - OrbitDriver Warning!]: Pegasus had a NaN Orbit and was removed.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
LmpClient.Harmony.OrbitDriver_UpdateFromParameters:UpdateFromParameters(OrbitDriver, Double&)
LmpClient.Harmony.OrbitDriver_UpdateFromParameters:PrefixUpdateFromParameters(OrbitDriver, Double&)
OrbitDriver:updateFromParameters_Patch1(Object)
LmpClient.Harmony.OrbitDriver_UpdateOrbit:UpdateOrbit(OrbitDriver, Boolean, Boolean&, Double&, Boolean&)
LmpClient.Harmony.OrbitDriver_UpdateOrbit:PrefixUpdateOrbit(OrbitDriver, Boolean, Boolean&, Double&, Boolean&)
OrbitDriver:UpdateOrbit_Patch1(Object, Boolean)
VesselPrecalculate:MainPhysics(Boolean)
VesselPrecalculate:FixedUpdate()

------
### **KSP.log**

[LOG 11:29:51.954] [LMP]: Locked to subspace -1, time: 5007.9050279
[LOG 11:29:51.971] Packing Pegasus for orbit
[LOG 11:29:52.034] Unpacking Pegasus
[LOG 11:29:52.089] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
[LOG 11:29:52.090] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
[LOG 11:29:52.101] [LMP]: Locked to subspace 1, time: 5008.03668641042
[LOG 11:29:52.113] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()

--
--
--

[LOG 11:29:55.498] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
[LOG 11:29:55.552] CheckEncounter: both intercept UTs are infinite
[LOG 11:29:55.559] CheckEncounter: both intercept UTs are infinite
[LOG 11:29:55.559] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()

--
--
--

[LOG 11:29:57.083] dT is NaN! tA: NaN, E: NaN, M: NaN, T: NaN
   at System.Environment.get_StackTrace()
   at Orbit.GetDTforTrueAnomaly(Double tA, Double wrapAfterSeconds)
   at PatchedConics._CalculatePatch(.Orbit p, .Orbit nextPatch, Double startEpoch, .SolverParameters pars, .CelestialBody targetBody)
   at PatchedConicSolver.Update()
[LOG 11:29:57.085] Packing Pegasus for orbit
[LOG 11:29:57.097] ObT : NaN
M : NaN
E : NaN
V : NaN
Radius: NaN
vel: [NaN, NaN, NaN]
AN: [-0.121126667573523, -0.0440197525915566, 0]
period: Infinity

[WRN 11:29:57.098] [LMP - OrbitDriver Warning!]: Pegasus had a NaN Orbit and was removed.
[LOG 11:29:57.099] Pegasus Unloaded
[LOG 11:29:57.104] [LMP]: Removing 7a3d479e-718f-4841-a7e1-cb35e8a1649d from the server
[LOG 11:29:57.106] [LMP]: Killing vessel 7a3d479e-718f-4841-a7e1-cb35e8a1649d. Reason: Corrupt vessel orbit
[LOG 11:29:57.111] [UIMasterController]: HideUI
[LOG 11:29:57.124] [HighLogic]: =========================== Scene Change : From FLIGHT to SPACECENTER (Async) =====================
[LOG 11:29:57.209] [OrbitDriver]: On-Rails SOI Transition from Kerbin to Sun.
 Transition UT Range: 5013.005 - 5013.025.
 Transition UT: 5013.025. Iterations: 24.
[LOG 11:29:57.211] setting new dominant body: Sun
FlightGlobals.mainBody: Sun
[EXC 11:29:57.245] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.246] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.246] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.246] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.247] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.247] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.247] NullReferenceException
	UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
	Vessel.Update ()
[EXC 11:29:57.384] NullReferenceException
	OrbitPhysicsManager.LateUpdate ()
[LOG 11:29:57.569] KbApp.OnDestroy Planet Resources
[LOG 11:29:57.570] KbApp.OnDestroy Unowned Info
[LOG 11:29:57.572] KbApp.OnDestroy Planet Info
[LOG 11:29:57.573] [UIApp] OnDestroy: KSPedia
[LOG 11:29:57.574] ScaleModList: listSize 41 maxListSize 747
[LOG 11:29:57.574] [UIApp] OnDestroy: ResourceDisplay
[LOG 11:29:57.575] ScaleModList: listSize 41 maxListSize 747
[LOG 11:29:57.576] KbApp.OnDestroy Vessel Crew
[LOG 11:29:57.577] KbApp.OnDestroy Vessel Info
[LOG 11:29:57.577] [UIApp] OnDestroy: DeltaVApp
[LOG 11:29:57.577] ScaleModList: listSize 41 maxListSize 747
[LOG 11:29:57.578] KbApp.OnDestroy NullName
[LOG 11:29:57.578] KbApp.OnDestroy Planet Parameters
[EXC 11:29:57.722] NullReferenceException: Object reference not set to an instance of an object
	FlightCamera.GetAutoModeForVessel (.Vessel v)
	FlightCamera+<Startup>c__Iterator0.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	FlightCamera:OnLevelLoaded(GameScenes)
	FlightCamera:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
[LOG 11:29:57.723] [UIMasterController]: HideUI
[LOG 11:29:58.774] [AddonLoader]: Instantiating addon 'CustomConfigsManager' from assembly 'ModuleManager'
[EXC 11:29:58.776] NullReferenceException: Object reference not set to an instance of an object
	FlightCamera.GetAutoModeForVessel (.Vessel v)
	FlightCamera+<Startup>c__Iterator0.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	FlightCamera:OnLevelLoaded(GameScenes)
	FlightCamera:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
[LOG 11:30:00.623] [UIMasterController]: HideUI
[LOG 11:30:00.946] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 11:30:00.951] Loading Depletion Nodes
[LOG 11:30:00.952] DepNodeCount:  0
[LOG 11:30:00.952] Loading Biome Nodes
[LOG 11:30:00.953] BiomeNodeCount:  0
[LOG 11:30:00.954] Loading Planet Nodes
[LOG 11:30:00.955] PlanetNodeCount:  0
[EXC 11:30:00.978] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_ship_velocity ()
	FloatingOrigin.FixedUpdate ()
[EXC 11:30:00.982] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_ship_velocity ()
	FloatingOrigin.FixedUpdate ()
[EXC 11:30:00.984] NullReferenceException: Object reference not set to an instance of an object
	AmbienceControl.Update ()
[EXC 11:30:00.985] NullReferenceException: Object reference not set to an instance of an object
	Vessel.Update ()

--
--
--

[EXC 11:30:04.837] NullReferenceException: Object reference not set to an instance of an object
	Vessel.Update ()
[WRN 11:30:05.132] [LMP] Adjusted time from: 4969.85858901115 to: 4973.40680901113 due to error: -3548.21999998694
[EXC 11:30:05.132] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_ship_velocity ()
	FloatingOrigin.FixedUpdate ()
[EXC 11:30:05.133] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_ship_velocity ()
	FloatingOrigin.FixedUpdate ()
[EXC 11:30:05.133] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_ship_velocity ()
	FloatingOrigin.FixedUpdate ()
[EXC 11:30:05.134] NullReferenceException: Object reference not set to an instance of an object
	AmbienceControl.Update ()
[EXC 11:30:05.135] NullReferenceException: Object reference not set to an instance of an object
	Vessel.Update ()

**Comment by sgtnoodle** [comment]
I was doing a pretty typical ascent to 125K above Kerbin when my vessel suddenly lost its velocity and started falling along a parabola. I was only at 70K or so when the glitch occurred. At the same time, two other people that were on the server dropped off. My UI was glitched out as described.

My KSP.log is 240MB in size and full of null reference exceptions!

**Comment by Aterfax** [comment]
Can also confirm random velocity losses when getting near to a launch's apoapsis.

**Comment by gavazquez** [comment]
Will have a look at it once able but it might take me a bit of time as I'm busy at work

**Comment by AdamRidley** [comment]
The fix seems to have an issue in that it only works for the active vessel. I am creating a satellite network and when I release my first satellite and time warp the satellite disappears. Presumably, because it it not the active vessel, its orbit suffers the same fate that  both the satellite and active vessel would have before the code change.

I will test further to see if this applies to any vessel within loading distance and report back.

**Comment by gavazquez** [comment]
Ok reopening it and will have a look

**Comment by gavazquez** [comment]
Ok guys let me know if now it's fixed
