### ISSUE TITLE
Initial connection timeout

### ISSUE THREAD

**Issue by SuperTemich2005** [LunaMultiplayer/LunaMultiplayer#321]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.8.1(.2694)

------------------------------------------------------------------------------

LMP version: 0.24.0

------------------------------------------------------------------------------

MODS: Luna multiplayer client, making history DLC and breaking grounds DLC

------------------------------------------------------------------------------

Expected behaviour: My friend should connect to my server

------------------------------------------------------------------------------

Current behaviour: He get "Initial connection timeout" problem

------------------------------------------------------------------------------

**Comment by gavazquez** [comment]
Not a bug. Check wiki and connection params

**Comment by SuperTemich2005** [comment]
You think I'd open an issue without checking wiki?! I checked the wiki and I didn't found any "connection params"! You'd better leave link to the topic you mention!

**Comment by gavazquez** [comment]
Well, 

1 There are active players at the moment and they don't have such problem
2 The network code is not from LMP, it's from lidgren
3 You're probably havving network issues on your own and not related to LMP. Check wiki, firewall, lan parameters etc

Creating a bug just because it doesn't work on your machine and without giving any detail about it besides "He get "Initial connection timeout" problem" it's not the right way to proceed

**Comment by SuperTemich2005** [comment]
Guess you have a point. Day passed, maybe we won't encounter that problem again. Maybe, it's because we are playing with hamachi. *Now*, thank you.

**Comment by gavazquez** [comment]
If you're playing with hamachi that's not the standard way of doing things
