### ISSUE TITLE
Running(stopping) Server with systemd?

### ISSUE THREAD

**Issue by fredlllll** [LunaMultiplayer/LunaMultiplayer#371]
heyo

so im trying to get the server to run as a systemd unit, but im having trouble with shutting it down. when starting it in a console adn sending sigint from a different terminal, it terminates as it should, puts out log that it saves etc. now when running it as systemd process, sending sigint results in immediate termination of the server, no log output. now im unsure if it actually saves or not. 

i also noticed that when ran as systemd unit one thread is completely blocking one cpu core with a bunch of kernel activity https://i.imgur.com/mpoGEqZ.png (edit: this seems to be connected to not having a proper stdin?)

i guess it just doesnt like being run as systemd unit? id really prefer this to docker

edit: nohup also shows the problem with one core at 100% =/
edit: docker image also has one core at 100% at all times. this does not happen when running it just in terminal

**Comment by JeanMarcZimmer** [comment]
I have the same problem, along with a few observations.

- SIGINT not working: Systemd apparently retrieves the PID of the first thread it starts. However, Mono is multi-threaded. And of course, the main process doesn't handle the SIGINT signal. Note that the same problem happens when starting from a bash script. I've tried using `Type=fork`, but it didn't work well.

- 100% CPU usage: I guess when started from a program (even a simple shell script), Mono reserves the power without using it. Not wanting to burn my CPU, I checked the temperature. Turns out it doesn't rise, so no worries. If you still don't want this, you can add the [`LimitCPU=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties) flag to your unit. Apparently there is also [`CPUQuota=`](https://stackoverflow.com/questions/29667758/use-of-cpuquota-in-systemd) but I couldn't find reliable information on that.

Generally though, I'd say that Mono really isn't made to run with automated scripts and systems. ~~And yet Windows Server exists...~~

**Comment by fredlllll** [comment]
i dont know if this is really monos fault, i have written software that ran on mono which ran as systemd units and i didnt have the 100% cpu problem. i also recall adding a signal handler for unix signals, and it worked. though i did start the listening for signals from the main thread. 

wonder how it would run on dotnet

**Comment by JeanMarcZimmer** [comment]
I don't know to be honest. I noticed something strange (and rather annoying) though : the service logs one character per line, making the reading of it excessively difficult.

**Comment by fredlllll** [comment]
lots of things to improve, sadly i dont have the time to fix it myself =/ (maybe i should play less ksp?)

but yes the log thing is irritating as hell, no idea why it does that, or rather why journald interprets every characters as a new line, while it shows up normally in a terminal (maybe the stream is flushed after every character?)

**Comment by JeanMarcZimmer** [comment]
The most irritating thing to think about here is that Mono comes with a service system, apparently similar to Systemd. I guess it'd be far easier to create a Mono service instead of a Systemd service, then using the latter to run mono-service. However, I have no idea how to create a Mono service.

**Comment by storm37000** [comment]
I ported the server software to .net core 3.1 (vastly superior to the obselete and should be dead by now .net framework).  This allowes it to be ran nativly on Windows, Linux, Linux ARM (rasperri pi), and OSX without a terrible system like mono.

**Comment by fredlllll** [comment]
so are you going to make a pullrequest or something?

**Comment by gavazquez** [comment]
Yes, feel free to do the PR when you feel like @storm37000

**Comment by storm37000** [comment]
i have to get it prepared for that, and make sure there are no issues.

**Comment by storm37000** [comment]
here is my fork for .net core; https://github.com/storm37000/LunaMultiplayer  I havent posted any binar releases, but if you have VS2019 you can right click on "Server" inside the "LMP Server" folder and click publis.  Then select which OS you would like to compile it for.

**Comment by fredlllll** [comment]
yeah im not gonna touch that. deleting half the codebase should not be included in making the server run on .netcore

**Comment by storm37000** [comment]
the client part cant run on .net core as it needs to work in the game engine, also i dont need all that appveyor bs.  Its not meant to be a pr as is, it would have to be merged in per vsproj.

**Comment by storm37000** [comment]
porting to .net core required remaking the whole VS project as it doesnt let you change .net version that majorly as alot of meta files are different.

**Comment by gavazquez** [comment]
Ok guys I ported this to net5. Hopefully this will solve all the issues
