### ISSUE TITLE
Include Dockerfile for server owners

### ISSUE THREAD

**Issue by 4669842** [LunaMultiplayer/LunaMultiplayer#56]
------------------------------------------------------------------------------

I created a example here: https://hub.docker.com/r/thesystem/lunamultiplayer/~/dockerfile/

Here is a log of a build: https://hub.docker.com/r/thesystem/lunamultiplayer/builds/b4ie73rdxrxrcfudnyzvdap/

------------------------------------------------------------------------------
Debug version is the only one currently working, production build hangs with Linux.
------------------------------------------------------------------------------

**Comment by lucas-jones** [comment]
Can also use this base image: https://github.com/mono/docker

**Comment by gavazquez** [comment]
What is docker? what will this allow us to do?

**Comment by gavazquez** [comment]
Hi @4669842 I saw your fork and it looks nice but would it be possible to get the files from the github releases?

You can see a JSON file here:
https://api.github.com/repos/LunaMultiplayer/LunaMultiplayer/releases/latest

And you'd need to get
assets[0].browser_download_url for DEBUG
assets[1].browser_download_url for RELEASE

I don't know much about docker but it hope it can handle JSON.
Also there must be an api so you can get the latest nighlty build from appveyour.
Example:
https://www.appveyor.com/docs/api/samples/download-artifacts-ps/

If you need help let me know but it looks nice!

**Comment by garyspencer** [comment]
@4669842 You are a scholar, this is exactly what I needed!

I recently discovered LMP, and I was trying to get my server migrated from DMP to LMP.  I was having trouble running with LMP via mono on ubuntu 14.04 (very similar to how DMP described installing on a raspi).  At odds with myself at how much effort I wanted to put into getting a custom install going, this saved the day!

```
<./Dockerfile exists as described>
docker build -t lmpserver .
docker run --rm -p 8800:8800/tcp -p 8801:8801/tcp -p 8800:8800/udp -p 8801:8801/udp lmpserver
```
Barring the extra changes needed to be added to that docker image in order to get a config/universe live, this is all you need to get a full blown server going... Impressive!

As the CI/CD Architect type at work, I am a big fan of using docker to simplify deployment and development.  I think docker in the dev & production workflows should be first class!  Anything I can do to help the cause?  

As I journey through setting my server up with docker, I think it might be worthwhile to figure out how to mount the Config/ && Universe/ during the run step to avoid having to layer it into the image, making hot-swapping of universes/configs rather seamless.  I believe as @gavazquez mentions the build artifact (.zip) may need to be sourced more dynamically unless that ci.appveyor job token stays valid for any :latest?
