### ISSUE TITLE
Implement Interpolation for orbit positioning

### ISSUE THREAD

**Issue by gavazquez** [LunaMultiplayer/LunaMultiplayer#69]
At the moment "Enable interpolation" setting in the options just generate problems as we are using **linear interpolation** in every parameter of the orbit.

I asked what type of interpolation would be the best [here](https://astronomy.stackexchange.com/questions/23938/how-can-i-interpolate-2-orbits) but I didn't received any conclusive answer.

Besides, I recorded orbit data during a stable orbit that started with this parameters:

![image](https://user-images.githubusercontent.com/12727761/35768174-10bd0bdc-08f8-11e8-864e-14d9c1d82fa4.png)

Here you have a txt file (formatted as csv) with all the orbit information for 30 seconds and taken every 100ms approximately

[OwnVesselNoAcceleration100MsInterval.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1691825/OwnVesselNoAcceleration100MsInterval.txt)

Here you have a txt file (formatted as csv) with all the orbit information for 30 seconds and taken every 100ms aproximately. This time the vessel was going full throttle towards prograde

[OwnVesselProgradeAcc100MsInterval.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1691826/OwnVesselProgradeAcc100MsInterval.txt)

In this last file, you have a txt with the orbit information received from ANOTHER vessel. I can't say what is the exact interval because it depends on the internet speed but I would say that is aproximately every 30/40ms

[AnotherVesselNoAccelerationReceivedMessages.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1691827/AnotherVesselNoAccelerationReceivedMessages.txt)

**Comment by Cjen1** [comment]
So I've graphed the results in this notebook: https://notebooks.azure.com/cjen01/libraries/LMPTest

The reason that some of the graphs are quite 'bouncy' is that the orbits that were used were 'perfect' orbits and hence aren't stable.

Also an idea, if the range of Argument of Periapsis and LAN is [0, 360] whereas the MNA is [-pi, pi]. Then if the vessel is in the vicinity of the discontinuity then the interpolation would be incorrect i.e. if two packets for LAN values: [350, 10] then the interpolation would return 180 rather than the more porbably correct 0.

Thus my suggested interpolation function:
```
double lerp(double a, double b, double t, double min, double max){
  if(b < a)
    return lerp(b,a,1-t,min,max);

  //by definition a > b at this point
  if(b - a < (max - min)/2){//ie probably not over discontinuity
    return (1-t) * a + t * b;
  } else {
    double a1 = a + (max - min);
    return lerp(a1, b, t, min, max);
  }
}
```

**Comment by gavazquez** [comment]
Hi @Cjen1 that lerp function is only for LAN? the others can still have the old interpolation function?

**Comment by Cjen1** [comment]
@gavazquez yep that would be the idea to implement it for the 'looping' values (Inclination, LPE, LAN, arg of Periapsis and MNA) however I haven't tested the function, and looking at it now I think that a slight adjustment is required:

```
double lerp(double a, double b, double t, double min, double max){
  if(b < a)
    return lerp(b,a,1-t,min,max);

  //by definition a > b at this point
  if(b - a < (max - min)/2){//ie probably not over discontinuity
    return (1-t) * a + t * b;
  } else {
    double a1 = a + (max - min);
    double res = lerp(a1, b, t, min, max);
    return res < max ? res : res - (max - min); //edit to make result fall within bounds
  }
}
```

But with that it should fix the interpolation issues over the boundaries. 
Also just to note: this should fix interpolation issues with orbits close to that boundary (0, 360 for example), however there may be other underlying issues, this should just fix one of them :)

**Comment by gavazquez** [comment]
I got this function to LERP angles between 0 and 360:

```
        public static double LerpAngle(double from, double to, float t)
        {
            var single = Repeat(to - from, 360);
            if (single > 180f)
            {
                single -= 360f;
            }
            return from + single * t;
        }

        public static double Repeat(double t, double length)
        {
            return t - Math.Floor(t / length) * length;
        }
```

How would it be in order to lerp between pi and -pi?

**Comment by gegy1000** [comment]
Similar to all the other solutions but supports a minimum/maximum value:
```csharp
var inclination = LerpAngle(inclination, Target.inclination, lerpPercentage, -Math.PI/2, Math.PI/2);
var eccentricity = Lerp(eccentricity, Target.eccentricity, lerpPercentage);
var semiMajorAxis = Lerp(semiMajorAxis, Target.semiMajorAxis, lerpPercentage);
var LAN = LerpAngle(LAN, Target.LAN, lerpPercentage, -Math.PI, Math.PI);
var argumentOfPeriapsis = LerpAngle(argumentOfPeriapsis, Target.argumentOfPeriapsis, lerpPercentage, 0.0, 2 *Math.PI);
var meanAnomalyAtEpoch = LerpAngle(meanAnomalyAtEpoch, Target.meanAnomalyAtEpoch, lerpPercentage, -Math.PI, Math.PI);
var epoch = Lerp(epoch, Target.epoch, lerpPercentage);

private static float Lerp(float v0, float v1, float lerpPercentage) {
    float easedPercentage = (1 - Math.cos(lerpPercentage * Math.PI)) / 2;
    return v0 * (1 - easedPercentage) + v1 * easedPercentage;
}

private static float LerpAngle(float v0, float v1, float lerpPercentage, float minAngle, float maxAngle) {
    float range = maxAngle - minAngle;
    while (v1 - v0 < minAngle) {
        v0 -= range;
    }
    while (v1 - v0 > maxAngle) {
        v0 += range;
    }
    return Lerp(v0, v1, lerpPercentage);
}
```

**Comment by gavazquez** [comment]
Hi @gegy1000 Unfortunately it doesn't work:

![tst](https://user-images.githubusercontent.com/12727761/35854132-d66eeb64-0b2f-11e8-890e-636df29fb58f.gif)

```
Vessel.orbitDriver.orbit.SetOrbit
(
	LerpAngle(Orbit[0], Target.Orbit[0], lerpPercentage, -Math.PI / 2, Math.PI / 2),
	Lerp(Orbit[1], Target.Orbit[1], lerpPercentage),
	Lerp(Orbit[2], Target.Orbit[2], lerpPercentage),
	LerpAngle(Orbit[3], Target.Orbit[3], lerpPercentage, -Math.PI, Math.PI),
	LerpAngle(Orbit[4], Target.Orbit[4], lerpPercentage, 0.0, 2 * Math.PI),
	LerpAngle(Orbit[5], Target.Orbit[5], lerpPercentage, -Math.PI, Math.PI),
	Lerp(Orbit[6], Target.Orbit[6], lerpPercentage),
	Body
);

private static double Lerp(double v0, double v1, double lerpPercentage)
{
	var easedPercentage = (1 - Math.Cos(lerpPercentage * Math.PI)) / 2;
	return v0 * (1 - easedPercentage) + v1 * easedPercentage;
}

private static double LerpAngle(double v0, double v1, double lerpPercentage, double minAngle, double maxAngle)
{
	var range = maxAngle - minAngle;
	while (v1 - v0 < minAngle)
	{
		v0 -= range;
	}
	while (v1 - v0 > maxAngle)
	{
		v0 += range;
	}
	return Lerp(v0, v1, lerpPercentage);
}
```

**Comment by gavazquez** [comment]
In case you want to extract orbital data yourselves, here you hava a mod that does that. Just put it in GameData folder and press the button "Get orbit data" once in flight. It will post the orbital data into the LOG at this format:

time;inclination;eccentricity;semi_major_axis;LAN;arg_of_periapsis;mean_anomaly_at_epoch;epoch

**Comment by gegy1000** [comment]
Looks like KSP uses degrees and not radians for all orbital variables. Could that be what's wrong here?

**Comment by Cjen1** [comment]
@gegy1000 yeah KSP does for everything but the Mean Anomoly at Epoch since it actually makes use of radians in the math. However that would not cause the issues shown in the gif...

@gavazquez does the magnitude of the jitter increase as the radius increases (distance not angle)
    - this will check whether it is the interpolation of the MNA that is the issue.

The only other thing I can think of is that there is some kind of dependency between the epoch and the MNA, could be tested by manually leaving one constant and vary the other?

**Comment by Damowerko** [comment]
Have you considered using kepler's laws and the equation for a parabola to solve for velocity and position then solving those values and transforming back into the required parameters about the orbit? Such an interpolation could be a lot more linear as these values do not change drastically for short durations. The result could be a lot smoother.

**Comment by dtrent1** [comment]
I don't have experience with C# coding (I use Python) but I do have lots in the area of orbital mechanics (I actually work for NASA doing mission architecting for advanced concepts). For me, one of the simplest references for the math of orbital mechanics is from Charles D. Brown's book Elements of Spacecraft Design. I have attached a PDF of chapter 3 on orbital mechanics. In it, the most concise information can be found in Tables 3.3 and 3.4 which summarize the various equations for calculating orbital elements for both elliptical and hyperbolic orbits. Information about the variables can be found throughout the chapter. Hope this helps with the interpolation tasks. I really would love a solid multiplayer mod to play with my brothers! Good Luck.

[Elements_of_Spacecraft_Design_----_(Chapter_3._Orbital_Mechanics).pdf](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1845348/Elements_of_Spacecraft_Design_----_.Chapter_3._Orbital_Mechanics.pdf)

**Comment by gavazquez** [comment]
hi @dtrent1 Thanks for the document, it's really interesting.

I actually asked this in the stackexchange but didn't get a conclusive answer perhaps you can help us on that:

https://astronomy.stackexchange.com/questions/23938/how-can-i-interpolate-2-orbits

**Comment by dtrent1** [comment]
@gavazquez,

Is the interpolation only being done in orbit with no external forces (i.e. no thrust or drag), or do you need it to work at all times (atmospheric flight and while thrusting)? The equations in the document I posted previously assume constant motion, i.e. no external forces.

If in orbit with no external forces, only mean anomaly will change with time, the other five will remain constant. This is because five of the parameters define the shape and rotation of the orbit, while only one is needed to define the position of the object on that orbit. External forces will act to change the other five orbital parameters. Thats where things get more challenging to interpolate.

For the simple case of no external forces, Mean anomaly, M, as a function if delta time, dt (30 millisecond in your case) is

M = M0 + n*dt     (1)

where M0 is the initial mean anomaly, and n is the mean motion

n = sqrt(mu/a^3)

where mu is the standard gravitational parameter of the orbited body and a is the semi-major axis.

**Comment by dtrent1** [comment]
@gavazquez I also forgot to mention, this interpolation is only good for elliptical orbits. I don't know how KSP defines hyperbolic orbits (escape trajectories). These orbits are defined by similar but different parameters. In this case, eccentricity is always greater than 1 and semi-major axis is negative (although the equations in the document I posted assume it semi-major axis as positive to make the equations similar to the eliptical case).

If you could provide the parameters KSP uses to define an escape trajectory, I can also help with figuring out interpolation in that scenario as well.

**Comment by dtrent1** [comment]
Ok, did some digging on how KSP parameterizes orbits. They use the same parameters, regardless of orbit type (elliptical or hyperbolic). However, semi-major axis becomes negative, eccentricity is greater than 1, and mean anomaly is negative when approaching periapsis and positive when receding. This is due to how hyperbolic orbits are mathematically modeled.

Knowing this, you can use the same equations provided above and just take the absolute value of the semi-major axis for calculating mean motion. so it should be as simple as:

M = M0 + sqrt(mu / abs(a^3)) * dt

where dt is the interpolation time in seconds.

**Comment by gavazquez** [comment]
hi @dtrent1 if you need to have a look at how KSP does the calculations you can use JustDecompile + De4Dot plugin. After that, just look at the "orbit" and "OrbitDriver" classes.

Regarding your formula, can I use linear interpolation for the other parameters? (epoch, eccentricity, LAN, etc)

**Comment by dtrent1** [comment]
@gavazquez No, that formula is only valid for MNA. Also, this formula is to predict the MNA at some time, dt, from a known epoch (as posed to calculating it between two known MNA values, which is what you currently are doing).

Looking at the rest of the thread and comments and I think I am starting to get a better Idea of what you are actually trying to do and what is going on. However, I think I am still a little bit confused about what exactly your are trying to achieve.

Is the purpose of this interpolation so that a client can predict the position of a vessel based on the most recent orbit information sent by the server? If so, why would you want to interpolate between an older data point and the most recent data point from the server? Would you not rather use the most recent data point from the server and try to predict (extrapolate) the vessels location until new information from the server is received to correct the prediction?

**Comment by gavazquez** [comment]
Not exaclty predict but "draw" the positions in between.

Here is an explanation:
http://www.gabrielgambetta.com/entity-interpolation.html

And a video:
https://www.youtube.com/watch?v=6EwaW2iz4iA

**Comment by dtrent1** [comment]
@gavazquez Ahh, I had actually stumbled upon Gabriel's post a while back when I was curious about this kind of thing.

In this case, I believe the linear interpolation scheme you have implemented (including the fixes for angles as discussed earlier) should do fine. I feel that the jumpiness you experience in the interpolated vessel is not due to an error in the interpolation, but rather error in the orbit data generated by KSP.

Looking at the source texts you provided in the first post, your interpolation is performing as expected based on that source data. The authoratative data says the vessel is jumping around:

![mna](https://user-images.githubusercontent.com/22297851/38165544-c6e0a9ec-34da-11e8-8b2d-31baba72f875.png)

As a result, your interpolation shows this same jumping, as is evident in the gif you posted. However, in your gif, you'll notice that the orbit line plotted (the gray line) doesn't seem to bounce around, just the position of the vessel in the orbit. This makes sense since the orbit is constant with no forces acting on the vessel, so just the position of the vessel changes with time, indicated by the mean anomaly (MNA). Granted, there are significant jumps in other parameters, such as argument of periaps and LAN, but they likely cancel each other out to show a consistent orbit path.

I think the real question is how did those deviation in the MNA occur in the source data? Is the game really spitting out that data (unlikely, since my vessels don't jump around on their orbits even near circular ones)? Rather, whatever code is retrieve the orbit information from KSP is likely causing the jumps in the MNA.

**Comment by gavazquez** [comment]
I agree.

This time I started with an orbit like this:
![image](https://user-images.githubusercontent.com/12727761/38173317-a002bd8c-35bc-11e8-8fe1-f7a958cde5e3.png)

Here you have the orbit data:
https://pastebin.com/s95LAsQG

Do you think that with the data I've sent you the linear interpolation can be used?

**Comment by dtrent1** [comment]
Yes, this data is much smoother:

![mna](https://user-images.githubusercontent.com/22297851/38173781-434f737e-3589-11e8-9caa-52189500b278.png)

 The linear interpolation you have should do well. Other than the likely kink in the data at about 350-500, this is very much what I expect to see. But again, the linear interpolation will show this original data well since the parameters are not changing much between time steps.

The next set of data you would want to test is the same starting orbit parameters and performing a burn at periapsis to see how well the interpolation works when other orbit parameter change which will change the shape of the orbit. Again, I think it will do well as the orbit parameters won't be changing that much between time steps. The only time linear interpolation may have an issue is as the orbit reaches ecentricity near 1. At that point orbit parameters will begin to change much more rapidly (think about how quickly your apoapsis increases when going to Minimus or a Kerbin escape). At that point you may need to switch to a quadratic or even cubic interpolation method to capture more of the non-linear nature. However, with such short time steps, you may still be able to get away with linear interpolation. If your data points are close enough together, even highly non-linear behavior could be interpolated linearly.

**Comment by gavazquez** [comment]
Hi @dtrent1 I got you the data for the same orbit. First 5-10 seconds I'm stable and then applied dV towards prograde:

https://pastebin.com/wZF2mMGR

On the meantime I'm trying to smooth out the interpolation when values reach ecc 0 and those edge cases. Also if you see that with that data another interpolation formula is better, let me know.

Thanks!

**Comment by gavazquez** [comment]
Hi @dtrent1 thanks a lot for confirming that linear interpolation might work.

Regarding the colon/semicolon probably is because Regional settings (the orbit extractor plugin was made in 5 minutes and I already lost the code of it)

About the first orbit on the first post it probably failed because the eccentricty was 0 aswell as the other parameters. I solved that using this on the code:

```CSharp
//Avoid lerping longitude of ascending node / arg of periapsis values when the inclination / eccentricity is close to 0 as it generate rounding errors!
if (Math.Abs(Orbit[0]) < 0.001 || Math.Abs(Orbit[1]) < 0.001)
    lerpPercentage = 1;

var inclination = LerpAngle(Orbit[0], Target.Orbit[0], lerpPercentage);
var eccentricity = Lerp(Orbit[1], Target.Orbit[1], lerpPercentage);
var semiMajorAxis = Lerp(Orbit[2], Target.Orbit[2], lerpPercentage);
var lan = LerpAngle(Orbit[3], Target.Orbit[3], lerpPercentage);
var argPeriapsis = LerpAngle(Orbit[4], Target.Orbit[4], lerpPercentage);
var meanAnomalyEpoch = LerpAngle(Orbit[5], Target.Orbit[5], lerpPercentage);
var epoch = Lerp(Orbit[6], Target.Orbit[6], lerpPercentage);
```
Regarding the LAN error... Looking at the graph it "jumps" at the same time of ECC and AOP so perhaps it was because physics engine took a while before kicking in...

Perhaps I should do the same as I do for inclination and eccentricty for LAN and avoid lerping when the value is close to 0/360...

**Comment by gavazquez** [comment]
Hi @dtrent1 perhaps you can help me on that as my math knowledge is quite forgotten after so many years...

So from what I discovered, here is how KSP handles each of the orbital parameters:

```CSharp
//Inclination must be a deg value between -180 and 180
var inclination = LunaMath.LerpDegAngle180(Orbit[0], Target.Orbit[0], lerpPercentage);
//Ecc must be a positive number from 0 to X
var eccentricity = LunaMath.Lerp(Orbit[1], Target.Orbit[1], lerpPercentage);
//Sma must be a positive number
var semiMajorAxis = LunaMath.Lerp(Orbit[2], Target.Orbit[2], lerpPercentage);
//LAN must be a deg value between 0 and 360
var lan = LunaMath.LerpDegAngle(Orbit[3], Target.Orbit[3], lerpPercentage);
//Arg of periapsis (LPE) must be a deg value between 0 and 360
var argPeriapsis = LunaMath.LerpDegAngle(Orbit[4], Target.Orbit[4], lerpPercentage);
//MNA must be a rad between -pi and pi
var meanAnomalyEpoch = LunaMath.LerpRadAnglePi(Orbit[5], Target.Orbit[5], lerpPercentage);
//Epoch is just the game time
var epoch = LunaMath.Lerp(Orbit[6], Target.Orbit[6], lerpPercentage);
```
For LAN, as it must be a value between 0 and 360 I use this LERP function:
This function is nice as it wraps the lerp angle and even if you enter an angle above 360 or below 0 it will return the correct lerp.

```CSharp
public static double LerpDegAngle(double from, double to, float t)
{
	var single = Repeat(to - from, 360);
	if (single > 180f)
	{
		single -= 360f;
	}
	return from + single * t;
}

private static double Repeat(double t, double length)
{
	return t - Math.Floor(t / length) * length;
}
```
The problem arises in the inclination.
This values must be lerped between -180 and 180 and the function above doesn't work. Do you know how can I lerp an angle in this case?

Also, the same issue happens with meanAnomalyEpoch but at the end is the same as the values are in radians

Thanks!

**Comment by dtrent1** [comment]
@gavazquez I played around with the LerpDegAngle function you provided. Unfortunately, I couldn't make it produce what I was expecting for interpolation. However, I was able to write some function which do perform as I expected for interpolation of angles with various wrapping conditions:

public static double LerpAngleDeg(double from, double to, float t, double wrapAngle)
{
	var retval = from + Repeat(to - from, 360) * t;
	if (retval > wrapAngle)
	{
		retval -= 360f;
	}
	return retval;
}

public static double LerpAngleRad(double from, double to, float t, double wrapAngle)
{
	var retval = from + Repeat(to - from, 2 * Math.Pi) * t;
	if (retval > wrapAngle)
	{
		retval -= 2 * Math.Pi;
	}
	return retval;
}

private static double Repeat(double t, double length)
{
	return t - Math.Floor(t / length) * length;
}

I don't know how to get the Pi constant in C++, so I just assumed its Math.Pi. Also, I looked into the ranges for the orbit parameters. It appears that MNA has a range from 0:2π when eccentricity < 1, but has a range of -inf:inf when eccentricity >= 1. So there will need to be a toggle to switch from LerpAngleRad to regular Lerp when eccentricity >= 1.

In these functions wrapAngle is the angle at which the values wrap back around. So for LAN and LPE you would use LerpAngleDeg(from, to, lerpPercentage, 360), for INC you would use LerpAngleDeg(from, to, lerpPercentage, 180), and for MNA, you will use LerpAngleRad(from, to, lerpPercentage, Math.Pi) when ECC < 1 and Lerp(from, to, lerpPercentage) otherwise.

**Comment by gavazquez** [comment]
Hi @dtrent1 Thanks a lot!

Your function works perfectly.
I created here a copy of your code: http://rextester.com/NBBFG85836 in case you want to test it aswell online.
Just for clarification, KSP runs on C# not C (which is much more complex)

Regarding the MNA I saw that the values still run in the range of -pi to pi

The value is PI on Apoapsis:

![image](https://user-images.githubusercontent.com/12727761/38294949-d0e3c504-37ec-11e8-9533-2b7f6513b2b9.png)

And 0 on periapsis:
![image](https://user-images.githubusercontent.com/12727761/38294973-e087607e-37ec-11e8-8b87-b3b0e4c8bd20.png)

And in orbits with ecc > 0 the value is close to 0:
![image](https://user-images.githubusercontent.com/12727761/38295140-5236a022-37ed-11e8-8cf3-c3e7f367738b.png)

Could it be that the values you've got are because edge cases?

**Comment by gavazquez** [comment]
Hi @dtrent1 I just made a test on negative numbers as I was watching a weird behaviour on KSP and the function doesn't work:

http://rextester.com/OUGRZ97998

```
Lerping from angle: -1,4 to angle: -2,1
0 Value: -1,4
0,1 Value: -0,841681460962447
0,2 Value: -0,283362921924894
0,3 Value: 0,274955658710631
0,4 Value: 0,833274156150212
0,5 Value: 1,39159265358979
0,6 Value: 1,94991131742126
0,7 Value: 2,50822964846896
0,8 Value: 3,06654831230042
0,9 Value: -2,65831866383147
1 Value: -2,1
```
All the interpolation numbers should have stayed negative but they wraped towards the positive side.

**Comment by gavazquez** [comment]
OK I think I managed to do it:

http://rextester.com/NQQED29892

**Comment by gavazquez** [comment]
Hi again @dtrent1 

I managed to fix almost every orbital parameter lerp unfortunately I've got a problem with the "inclination parameter"

![bug](https://user-images.githubusercontent.com/12727761/38308825-8cd6049a-3818-11e8-9317-3cb6c550d6a7.gif)

In this GIF the vessel is changing from heading 110 to heading 80. And this wobbling appears.
The catch is that in KSP the inclination angles goes from 0 to 180 so the lerping doesn't work correctly.

In this example the inclination values were aprox:
```
Init: Inclination 2º
Init+1: Inclination 1º
**Init+2: Inclination 0º**
Init+3: Inclination 1º
End: Inclination 2º
```

The problem is that the lerp doesn't know that he mas go **trough** the 0º position
So in this case, if I receive a packet from inc angle : 0.8 and a packet to incl angle 1
The lerp in 5 steps would produce values:
0.8/0.85/0.9/0.95/1
But what I need are values that go trough the angle "0" like:
0.8/0.3/0/0.5/1

Do you know how can I solve this? perhaps by using the other orbital parameters?

**Comment by dtrent1** [comment]
@gavazquez you are right, my function was not working in the case you pointed out. Your functions almost work. However, when wrapping from 1 to 359 it fails. However, I think I have made a slight modification that makes this case work and does not affect any of the other wrap scenarios:

```c#
public static double LerpAngleDeg(double from, double to, float t, double wrapAngle)
        {
           var single = Repeat(to - from, 360);
            
            if (single > 180f)
            {
                single -= 360f;
            }
            
            var angle = from + single * t;
            
            if (angle > wrapAngle)
                angle -= 360;
            if (angle <= -wrapAngle)
                angle += 360;
            if (angle <= wrapAngle - 360)
                angle += 360;
            
            return angle;
        }
```

**Comment by dtrent1** [comment]
@gavazquez As for KSP having INC values between 0 and 180, are you sure of this? I thought they were from -180 to 180? I wonder if the bounds on certain parameters are different when in orbit vs flight?

**Comment by gavazquez** [comment]
@dtrent1 Yes I was surprised aswell but even KSP doesn't allow you to go above 180:

![image](https://user-images.githubusercontent.com/12727761/38313504-7eacec74-3824-11e8-8710-cd488c5d3856.png)

And if you enter a negative value it's switched to positive when physics engine starts

![obt](https://user-images.githubusercontent.com/12727761/38313591-b108e074-3824-11e8-9533-614bf6f81be8.gif)

**Comment by dtrent1** [comment]
@gavazquez Wow, KSP definitely takes an unorthodox way of defining ranges for parameters. With INC being between 0 and 180, it is going to be difficult to write a lerp function that wraps around 0 but is positive in both direction. If you consider a condition of transitioning through the zero point going from 2 deg to 4 deg, how should the lerp function know you want to go through zero and not just from 2 deg to 4 deg without passing through zero? Looking at additional parameters seems like it will be the only way to tell what is happening in this scenario. I suspect it will be some combination of LAN and AOP. But as for how, that is becoming increasingly more complex...

**Comment by gavazquez** [comment]
@dtrent1 Yes... I'm doing the same but I also don't have any idea... Will try more approaches tomorrow

**Comment by dtrent1** [comment]
@gavazquez Ok, I think I have something figured out. We can do a simple transformation to the INC value based on LAN and AOP of the from and to orbits. This will allow us to use the interpolation functions already written.

From playing around with some numbers, I think if we check the differences in LAN and AOP of the from and to orbits and they sum to about 360, then just calculate the absolute value of the lerped angle, while multiplying one of the INC inputs by -1. Don't ask me to explain why it works, because I am not sure I know. But it seems to produce the results we are looking for.

In code, I think what it will look like is a check of the LAN and AOP values of the from and two orbits:

```python3
errbnd = 1e-2
# calculate the total angle difference in LAN and AOP from initial to final orbit
anglediff = abs(Orbit[3] - Target.Orbit[3]) + abs(Orbit[4] - Target.Orbit[4])
# check if total angle difference is about 360, to account for rounding errors in the physics engine
if anglediff > (1-errbnd) * 360 and anglediff < (1+errbnd) * 360: 
    # lerp the INC value through zero, positive on both sides
    inclination = abs(LerpAngleDeg(-1 * Orbit[3], Target.Orbit[3], lerpPercentage, 180))
else:
    # at this point, we know the value is not dealing with any wrapping, so we can just use
    # the regular lerp function
    inclination = Lerp(Orbit[3], Target.Orbit[3], lerpPercentage)
```

**Comment by dtrent1** [comment]
@gavazquez Her is an example of the MAN value on hyperbolic trajectories. You can see that it is well outside the 2π range under circular orbit conditions.
![capture](https://user-images.githubusercontent.com/22297851/38334501-245f79ba-3821-11e8-813f-ed035dbc3500.PNG)
![capture2](https://user-images.githubusercontent.com/22297851/38334505-267e87a4-3821-11e8-9e52-c4b4efe32ebe.PNG)

**Comment by gavazquez** [comment]
Hi @dtrent1 I will check your code tomorrow.

Regarding your screenshots I cannot confirm at this moment as I didn't saw the code of this mod but you shouldn't trust FlightEnginieer as it might show the data parsed in a more readable way. For this case you should use the LMP-Debug-ShowOrbitData panel as it shows the raw values directly and in the same format as KSP handles them

**Comment by dtrent1** [comment]
You are right, numbers from FlightEnginieer does provide different numbers. Interesting. However, still has the same story. The MNA values are still outside of the 2π range when in a circular orbit.

![capture](https://user-images.githubusercontent.com/22297851/38338652-0a03b4be-3830-11e8-93d2-23e285d42cc8.PNG)
![capture2](https://user-images.githubusercontent.com/22297851/38338653-0bbb9f06-3830-11e8-9828-917872486640.PNG)

**Comment by gavazquez** [comment]
Hi @dtrent1 you're totally right, seeing that this is the case I'll make the MNA follow a normal lerp if ecc < 1 and then accept whatever range if ecc >=1.

Gonna try the code you put yesterday and see if I can make it work

**Comment by gavazquez** [comment]
Hi @dtrent1 I'm still experimenting with your changes as I still se the wobbling, curiously  the code is fine but I must be missing something as in ksp it still wobbles when close to 90/270...

![image](https://user-images.githubusercontent.com/12727761/38364217-f9cfd296-38d7-11e8-8d9b-4bb86bec1a4f.png)

Code: http://rextester.com/PGBV9014

**Comment by gavazquez** [comment]
hi @dtrent1 I've been investigatin it more and I guess we need something similar as we you did with the inclination but for LAN and ArgPeriapsis.

Whenever you cross the "90" degree mark and interpolate **LAN**. We must make sure that whatever numbers you get they must pass trough the angle "0"º. In the case of AOP in this case it doesn't matter.

On the other side when crossing the "270" degree mark to interpolate the **AOP**. We must make sure that the numbers cross the angle "0"º. And in this case the **LAN** doesn't matter

**Comment by gavazquez** [comment]
Regarding the code I'm using an error bound of 0.10 as sometimes it didn't detected the boundary.

This is the full code with the green boundary case values):
http://rextester.com/CZW77232

**Comment by gavazquez** [comment]
Finally! Closed with commit https://github.com/LunaMultiplayer/LunaMultiplayer/commit/7285ff0bafbafc18997deabf31988c5c15acdf74

**Comment by dtrent1** [comment]
@gavazquez This looks really good. Sorry I've been MIA for a bit. I've been on travel for work. I hope you were able to get the last little bug ironed out. This may be one of those scenarios where the last little 1% to reach perfection isn't worth the time and effort to reach it in the grand scheme of things.

Looking at the data you posted, you are right that there is something going on with the inclination, how it starts at 1.5 at the top of the green block, moves through zero, and on to 1.6. However, in the yellow block just bellow, it does another transition through zero, where I would have expected it to continue to increase after the first transition through zero. Obviously, this is resulting in the jumping. My observation of the data is that the green block has an Inc transition through zero because Lan moves through its corresponding transition. This is expected and good. However, looking at the last line of the green block and the first line of the next yellow block, the FROM orbit in the yellow block becomes the last interpolation between the FROM and TARGET orbits in the green block. The issue is that the Inc value from the final interpolation in the green block is on the other side of its transition through zero, at 1.6, which is good, but the Lan parameter for the FROM orbit in the yellow block inherits a pre-transition value of 356.9 from the last interpolation. So now the second yellow block FROM and TARGET orbits show another transition, resulting in the jumping.

If none of that made sense, thats ok, I know it was probably confusing. The key is I believe the issue is that the Target orbit is very close to the transition point in Lan and the interpolation is too course to capture the transition correctly. My suggestion would be increase the resolution of interpolation by interpolating more lengths between the FROM and TARGET orbits. In fact, you don't even really need to increase the resolution, maybe just make sure your final interpolation length is much closer to 1 such that your final interpolation values are very close to the TARGET orbit's parameters.

**Comment by gavazquez** [comment]
Hi @dtrent1 

Yes I got tired of playing with orbital parameters. What I'm doing now is that I play with the position vector and the velocity vector. It's way more easy to interpolate that than the orbital parameters.

It actually looks good and if you want to try it just grab the latest nightly version and activate the interpolation in the settings :)

It has some issues with ground positioning but in the sky it works very nice even with sync times of 250ms.
