### ISSUE TITLE
People getting kicked on scene change (2 bugs here) 0.1.13.597 nightly

### ISSUE THREAD

**Issue by RacerXx** [LunaMultiplayer/LunaMultiplayer#79]
(bug 1) People getting kicked on scene change. Alot of times going back to tracking station fixes issues with not being able to see somebody in map view even after both people are "sync'd"before and after a intercept. Goto tracking station then coming back to vessel will fix it alot of times. BUT doing that scene change can also DC other people (bug 2) (3 out of 4 clients got dc'd) The problem is there is nothing in logs server or client. Lothsahn suggested more debug messages in the log files

Mechjeb was used. However time warp was used in such a way that did not interfere with sync or in some cases ie before landing was not used at all and all syncing on both clients was confirmed before any maneuvers were performed. Using this mechjeb method allowed viewing of side by side landing on mun with 2 clients without issues (nice work BTW) In this case Mechjeb was used all the way to the mun with time warp. Time warp was not used however for final descent burn to surface. (thats the key) sync and let mechjeb deorbit but descend without timewarp and always sync both clients before any maneuver.

**Comment by BCSpazer** [comment]
More Information on client kicked on scene change:
OS: 
Windows 10 Pro Version 1790, Build 16299.192
------------------------------------------------------------------------------
KSPVersion: 
1.3.1.1891
------------------------------------------------------------------------------
LMP version (include the build number if you are using a nighly build): 
0.1.14.608 (Server and Client)
------------------------------------------------------------------------------
MODS (add link to download them): 
https://github.com/MuMech/MechJeb2/tree/29d9b1ba7e75a325476b9a4f5712d1970c09b840/MechJeb2
------------------------------------------------------------------------------
Expected behaviour: 
Scene change from Tracking Station to In Flight
------------------------------------------------------------------------------
Current behaviour: 
Crash to Main Menu and disconnect from server.
------------------------------------------------------------------------------
Steps to reproduce:
Go to Tracking Station from Space Center, Select Vessel from Vessel List, Click Fly
------------------------------------------------------------------------------
Files:
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1732082/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1732091/output_log.txt)
[Server Files.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1732103/Server.Files.zip)

**Comment by gavazquez** [comment]
Seems that it was on the scenario system. Made it so scenarios are only saved in flight.

Check latest nighlty

**Comment by BCSpazer** [comment]
KSP is still crashing on scene changes. Same information as above with new logs attached. 

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1733819/KSP.log)
[KSP (2).log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1733820/KSP.2.log)
[Server Files.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1733824/Server.Files.zip)

**Comment by gavazquez** [comment]
Hi @BCSpazer on your logs I don't see any error and it doesn't look like you were kicked to main menu as in the last lines it states that you were on tracking station:

[LOG 20:23:58.371] [HighLogic]: =========================== Scene Change : From FLIGHT to TRACKSTATION (Async) =====================

What did happen this time?

**Comment by BCSpazer** [comment]
That didn't take log...
Moving from VAB to Launch Pad. Crash to Windows. Running latest nightly.

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1734247/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1734248/output_log.txt)
[Server Files.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1734249/Server.Files.zip)

**Comment by gavazquez** [comment]
I looked at your logs but there is not any exception or anything that can guide me to find it. (on the first report there was a exception that helped me to do the fix)

Also I saw that you're running other mods so I cannot be sure if the error is in LMP or in the other mods.

Can you try running LMP without mods and see if that happens aswell?

**Comment by BCSpazer** [comment]
Server disconnect and dump to Main Menu after clicking on Tracking Station from Space Center.
Server and client on 633 nightly.
Looks like the logs caught something this time.

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1740723/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1740724/output_log.txt)
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1740725/Universe.zip)

**Comment by gavazquez** [comment]
Again the goddamn scenario system....

I surrounded the code in a try catch. Should work fine now
